#!/usr/bin/env python3

import sys
from pathlib import Path
from subprocess import Popen, PIPE
from timeit import default_timer as timer


class Color:
    RESET = "\033[1;0;40m"
    ERROR = "\033[1;31;40m"
    SUCCESS = "\033[1;32;40m"
    INFO = "\033[1;36;40m"


class TestRunner:
    executable: str
    test_dir: Path

    def __init__(self, executable: str, tests_dir: str):
        self.executable = executable
        self.test_dir = sorted(list(Path(tests_dir).glob("*")))

    def run(self):
        total = 0
        passed = 0
        for filename in self.test_dir:
            if str(filename)[-2:] == ".a":
                continue
            total += 1
            if self._exec_file(str(filename)):
                passed += 1
        if total == passed:
            color = Color.SUCCESS
        else:
            color = Color.ERROR
        sys.stdout.write(f"{color}{passed} out of {total} tests passed{Color.RESET}\n")
        sys.stdout.flush()

    def _exec_file(self, filename) -> bool:
        sys.stdout.write(f"{Color.INFO}Test {filename}{Color.RESET}\t")
        sys.stdout.flush()
        # Do work here
        start = timer()
        process = Popen([self.executable], stdin=PIPE, stdout=PIPE)
        process.stdin.write(bytes(open(filename).read(), 'utf-8'))
        cmd_output, errors = process.communicate()
        time_taken = round(timer() - start, 4)
        expected_output = bytes(open(filename+".a").read(), 'utf-8')
        if cmd_output == expected_output:
            sys.stdout.write(f"{Color.SUCCESS}{Color.RESET} Time Taken: {time_taken}s\n")
            sys.stdout.flush()
            return True
        else:
            sys.stdout.write(f"{Color.ERROR}FAILED{Color.RESET}\n")
            if errors:
                sys.stdout.write(f"\tExpected:\n{expected_output.decode('utf-8')}\n\tGot:\n{errors.decode('utf-8')}{Color.RESET}\n")
            else:
                sys.stdout.write(f"\tExpected:\n{expected_output.decode('utf-8')}\n\tGot:\n{cmd_output.decode('utf-8')}{Color.RESET}\n")
            sys.stdout.flush()
            return False


def main():
    if len(sys.argv) < 2:
        print(f"{Color.ERROR}Usage: coursera_testrunner <executable> <tests_directory>{Color.RESET}")
        sys.exit(1)

    runner: TestRunner = TestRunner(sys.argv[1], sys.argv[2])
    runner.run()


if __name__ == "__main__":
    main()
