#!/usr/bin/env bash

options="Restart Audio"

script_select() {
    case "$1" in
    "Restart Audio")
        i3-msg "exec --no-startup-id killall pulseaudio"
        i3-msg "exec --no-startup-id pulseaudio --start"
        notify-send "Audio drivers restarted"
        ;;
    esac
}

case "$1" in
"options")
    echo -e $options
    ;;
"select")
    option=$(echo -e $options | rofi -theme sidetab -dmenu -p "Select script")
    script_select $option
    ;;
*)
    echo "No options provided"
    ;;
esac

