#!/bin/bash

function intellij_reset() {
    case $1 in
        idea)
            rootDir=".IntelliJIdea*"
            javaPrefDir="idea"
            ;;
        pycharm)
            rootDir=".PyCharm*"
            javaPrefDir="pycharm"
            ;;
        clion)
            rootDir=".CLion*"
            javaPrefDir="clion"
            ;;
        goland)
            rootDir=".GoLand*"
            javaPrefDir="goland"
            ;;
        *)
            rootDir=".IntelliJIdea*"
            javaPrefDir="idea"
            ;;
    esac

    evalKey="~/$rootDir/config/eval"
    echo "removing evaluation key $evalKey"
    rm -rf ~/$rootDir/config/eval

    javaUserPref="~/.java/.userPrefs/jetbrains/$javaPrefDir"
    echo "removing java user pref $javaUserPref"
    rm -rf ~/.java/.userPrefs/jetbrains/$javaPrefDir

    intellijOther="~/$rootDir/config/options/other.xml"
    echo "resetting evalsprt in $intellijOther"
    sed -i '/evlsprt/d' ~/$rootDir/config/options/other.xml

    echo "resetting evalsprt in prefs.xml"
    sed -i '/evlsprt/d' ~/.java/.userPrefs/prefs.xml

    echo "change date file"
    find ~/$rootDir -type d -exec touch -t $(date +"%Y%m%d%H%M") {} +;
    find ~/$rootDir -type f -exec touch -t $(date +"%Y%m%d%H%M") {} +;
}

intellij_reset $1

# rm  -rf ~/.IntelliJIdea*/config/eval
# rm  -rf ~/.GoLand*/config/eval
# rm  -rf ~/.WebStorm*/config/eval
# rm  -rf ~/.CLion*/config/eval

# rm -rf ~/.java/.userPrefs/jetbrains/idea
# rm -rf ~/.java/.userPrefs/jetbrains/goland
# rm -rf ~/.java/.userPrefs/jetbrains/webstorm
# rm -rf ~/.java/.userPrefs/jetbrains/clion

# sed -i '/evlsprt/d' ~/.IntelliJIdea*/config/options/other.xml
# sed -i '/evlsprt/d' ~/.GoLand*/config/options/other.xml
# sed -i '/evlsprt/d' ~/.WebStorm*/config/options/other.xml
# sed -i '/evlsprt/d' ~/.CLion*/config/options/other.xml

# sed -i '/evlsprt/d' ~/.java/.userPrefs/prefs.xml


# find ~/.CLion* -type d -exec touch -t $(date +"%Y%m%d%H%M") {} +;
# find ~/.CLion* -type f -exec touch -t $(date +"%Y%m%d%H%M") {} +;

# find ~/.IntelliJIdea* -type d -exec touch -t $(date +"%Y%m%d%H%M") {} +;
# find ~/.IntelliJIdea* -type f -exec touch -t $(date +"%Y%m%d%H%M") {} +;

# find ~/.GoLand* -type d -exec touch -t $(date +"%Y%m%d%H%M") {} +;
# find ~/.GoLand* -type f -exec touch -t $(date +"%Y%m%d%H%M") {} +;
