#!/bin/bash

# Theme
insidecolor=00000000
ringcolor=ffffffff
keyhlcolor=d23c3dff
bshlcolor=d23c3dff
separatorcolor=00000000
insidevercolor=00000000
insidewrongcolor=d23c3dff
ringvercolor=ffffffff
ringwrongcolor=ffffffff
verifcolor=ffffffff
timecolor=ffffffff
datecolor=ffffffff
loginbox=00000066
font="sans-serif"
locktext='Type password to unlock...'

revert() {
  rm /tmp/*screen*.png
  xset dpms 0 0 0
}

lockscreen() {
    i3lock \
        -t -i "$1" \
        --timepos='x+110:h-70' \
        --datepos='x+43:h-45' \
        --clock --date-align 1 --datestr "$locktext" \
        --insidecolor=$insidecolor --ringcolor=$ringcolor --line-uses-inside \
        --keyhlcolor=$keyhlcolor --bshlcolor=$bshlcolor --separatorcolor=$separatorcolor \
        --insidevercolor=$insidevercolor --insidewrongcolor=$insidewrongcolor \
        --ringvercolor=$ringvercolor --ringwrongcolor=$ringwrongcolor --indpos='x+280:h-70' \
        --radius=20 --ring-width=4 --veriftext='' --wrongtext='' \
        --verifcolor="$verifcolor" --timecolor="$timecolor" --datecolor="$datecolor" \
        --time-font="$font" --date-font="$font" --layout-font="$font" --verif-font="$font" --wrong-font="$font" \
        --noinputtext='' --force-clock
}

trap revert HUP INT TERM
xset +dpms dpms 0 0 5
scrot -d 1 /tmp/locking_screen.png
convert -blur 0x8 /tmp/locking_screen.png /tmp/screen_blur.png
convert -composite /tmp/screen_blur.png ~/dotfiles/morty.png -gravity South -geometry -20x1200 /tmp/screen.png
lockscreen /tmp/screen.png
revert
exit 0
